USE [master]
GO
/****** Object:  Database [FIAS]    Script Date: 20.07.2015 22:37:31 ******/
CREATE DATABASE [FIAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FIAS', FILENAME = N'E:\DB\FIAS.mdf' , SIZE = 16698368KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FIAS_log', FILENAME = N'E:\DB\FIAS_log.ldf' , SIZE = 26816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [FIAS] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FIAS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FIAS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FIAS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FIAS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FIAS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FIAS] SET ARITHABORT OFF 
GO
ALTER DATABASE [FIAS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FIAS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FIAS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FIAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FIAS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FIAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FIAS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FIAS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FIAS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FIAS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FIAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FIAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FIAS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FIAS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FIAS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FIAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FIAS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FIAS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FIAS] SET  MULTI_USER 
GO
ALTER DATABASE [FIAS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FIAS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FIAS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FIAS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [FIAS] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'FIAS', N'ON'
GO


USE [FIAS]
GO

/****** Object:  Table [dbo].[House]    Script Date: 20.07.2015 22:37:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[House](
	[POSTALCODE] [char](6) NULL,
	[REGIONCODE] [char](2) NULL,
	[IFNSFL] [char](4) NULL,
	[TERRIFNSFL] [char](4) NULL,
	[IFNSUL] [char](4) NULL,
	[TERRIFNSUL] [char](4) NULL,
	[OKATO] [char](11) NULL,
	[OKTMO] [varchar](11) NULL,
	[UPDATEDATE] [datetime] NOT NULL,
	[HOUSENUM] [nvarchar](20) NULL,
	[ESTSTATUS] [int] NOT NULL,
	[BUILDNUM] [nvarchar](10) NULL,
	[STRUCNUM] [nvarchar](10) NULL,
	[STRSTATUS] [int] NULL,
	[HOUSEID] [char](36) NOT NULL,
	[HOUSEGUID] [char](36) NOT NULL,
	[AOGUID] [char](36) NOT NULL,
	[STARTDATE] [datetime] NOT NULL,
	[ENDDATE] [datetime] NOT NULL,
	[STATSTATUS] [int] NOT NULL,
	[NORMDOC] [nvarchar](36) NULL,
	[COUNTER] [int] NOT NULL,
	[CADNUM] [nvarchar](100) NULL,
	[DIVTYPE] [int] NOT NULL
) ON [PRIMARY]

GO


/****** Object:  Table [dbo].[HouseInterval]    Script Date: 20.07.2015 22:37:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HouseInterval](
	[POSTALCODE] [nvarchar](50) NULL,
	[IFNSFL] [nvarchar](50) NULL,
	[TERRIFNSFL] [nvarchar](50) NULL,
	[IFNSUL] [nvarchar](50) NULL,
	[TERRIFNSUL] [nvarchar](50) NULL,
	[OKATO] [nvarchar](50) NULL,
	[OKTMO] [nvarchar](50) NULL,
	[UPDATEDATE] [datetime] NOT NULL,
	[INTSTART] [bit] NOT NULL,
	[INTEND] [bit] NOT NULL,
	[HOUSEINTID] [nvarchar](50) NOT NULL,
	[INTGUID] [nvarchar](50) NOT NULL,
	[AOGUID] [nvarchar](50) NOT NULL,
	[STARTDATE] [datetime] NOT NULL,
	[ENDDATE] [datetime] NOT NULL,
	[INTSTATUS] [bit] NOT NULL,
	[NORMDOC] [nvarchar](50) NULL,
	[COUNTER] [bit] NOT NULL
) ON [PRIMARY]

GO


/****** Object:  Table [dbo].[Landmark]    Script Date: 20.07.2015 22:37:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Landmark](
	[LOCATION] [nvarchar](500) NOT NULL,
	[POSTALCODE] [nvarchar](50) NULL,
	[IFNSFL] [nvarchar](50) NULL,
	[TERRIFNSFL] [nvarchar](50) NULL,
	[IFNSUL] [nvarchar](50) NULL,
	[TERRIFNSUL] [nvarchar](50) NULL,
	[OKATO] [nvarchar](50) NULL,
	[OKTMO] [nvarchar](50) NULL,
	[UPDATEDATE] [datetime] NOT NULL,
	[LANDID] [nvarchar](50) NOT NULL,
	[LANDGUID] [nvarchar](50) NOT NULL,
	[AOGUID] [nvarchar](50) NOT NULL,
	[STARTDATE] [datetime] NOT NULL,
	[ENDDATE] [datetime] NOT NULL,
	[NORMDOC] [nvarchar](50) NULL
) ON [PRIMARY]

GO


/****** Object:  Table [dbo].[NormativeDocument]    Script Date: 20.07.2015 22:37:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NormativeDocument](
	[NORMDOCID] [nvarchar](50) NOT NULL,
	[DOCNAME] [nvarchar](max) NULL,
	[DOCDATE] [datetime] NULL,
	[DOCNUM] [nvarchar](50) NULL,
	[DOCTYPE] [bit] NOT NULL,
	[DOCIMGID] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


/****** Object:  Table [dbo].[Object]    Script Date: 20.07.2015 22:37:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Object](
	[AOGUID] [char](36) NOT NULL,
	[FORMALNAME] [nvarchar](120) NOT NULL,
	[REGIONCODE] [char](2) NOT NULL,
	[AUTOCODE] [char](1) NOT NULL,
	[AREACODE] [char](3) NOT NULL,
	[CITYCODE] [char](3) NOT NULL,
	[CTARCODE] [char](3) NOT NULL,
	[PLACECODE] [char](3) NOT NULL,
	[PLANCODE] [char](4) NOT NULL,
	[STREETCODE] [char](4) NULL,
	[EXTRCODE] [char](4) NOT NULL,
	[SEXTCODE] [char](3) NOT NULL,
	[OFFNAME] [nvarchar](120) NULL,
	[POSTALCODE] [char](6) NULL,
	[IFNSFL] [char](4) NULL,
	[TERRIFNSFL] [char](4) NULL,
	[IFNSUL] [char](4) NULL,
	[TERRIFNSUL] [char](4) NULL,
	[OKATO] [char](11) NULL,
	[OKTMO] [varchar](11) NULL,
	[UPDATEDATE] [datetime] NOT NULL,
	[SHORTNAME] [nvarchar](10) NOT NULL,
	[AOLEVEL] [int] NOT NULL,
	[PARENTGUID] [char](36) NULL,
	[AOID] [char](36) NOT NULL,
	[PREVID] [char](36) NULL,
	[NEXTID] [char](36) NULL,
	[CODE] [varchar](17) NULL,
	[PLAINCODE] [varchar](15) NULL,
	[ACTSTATUS] [int] NOT NULL,
	[CENTSTATUS] [int] NOT NULL,
	[OPERSTATUS] [int] NOT NULL,
	[CURRSTATUS] [int] NOT NULL,
	[STARTDATE] [datetime] NOT NULL,
	[ENDDATE] [datetime] NOT NULL,
	[NORMDOC] [nvarchar](36) NULL,
	[LIVESTATUS] [int] NOT NULL,
	[DIVTYPE] [int] NOT NULL
) ON [PRIMARY]

GO


ALTER TABLE [dbo].[House]  WITH NOCHECK ADD  CONSTRAINT [CK_House_BUILDNUM] CHECK  ((len([BUILDNUM])>=(0)))
GO
ALTER TABLE [dbo].[House] CHECK CONSTRAINT [CK_House_BUILDNUM]
GO
ALTER TABLE [dbo].[House]  WITH NOCHECK ADD  CONSTRAINT [CK_House_HOUSENUM] CHECK  ((len([HOUSENUM])>=(1)))
GO
ALTER TABLE [dbo].[House] CHECK CONSTRAINT [CK_House_HOUSENUM]
GO
ALTER TABLE [dbo].[House]  WITH NOCHECK ADD  CONSTRAINT [CK_House_OKTMO] CHECK  ((len([OKTMO])>=(8)))
GO
ALTER TABLE [dbo].[House] CHECK CONSTRAINT [CK_House_OKTMO]
GO
ALTER TABLE [dbo].[House]  WITH NOCHECK ADD  CONSTRAINT [CK_House_STRUCNUM] CHECK  ((len([STRUCNUM])>=(0)))
GO
ALTER TABLE [dbo].[House] CHECK CONSTRAINT [CK_House_STRUCNUM]
GO
ALTER TABLE [dbo].[HouseInterval]  WITH NOCHECK ADD  CONSTRAINT [CK_HouseInterval_OKTMO] CHECK  ((len([OKTMO])>=(8)))
GO
ALTER TABLE [dbo].[HouseInterval] CHECK CONSTRAINT [CK_HouseInterval_OKTMO]
GO
ALTER TABLE [dbo].[Landmark]  WITH NOCHECK ADD  CONSTRAINT [CK_Landmark_LOCATION] CHECK  ((len([LOCATION])>=(1)))
GO
ALTER TABLE [dbo].[Landmark] CHECK CONSTRAINT [CK_Landmark_LOCATION]
GO
ALTER TABLE [dbo].[Landmark]  WITH NOCHECK ADD  CONSTRAINT [CK_Landmark_OKTMO] CHECK  ((len([OKTMO])>=(8)))
GO
ALTER TABLE [dbo].[Landmark] CHECK CONSTRAINT [CK_Landmark_OKTMO]
GO
ALTER TABLE [dbo].[NormativeDocument]  WITH NOCHECK ADD  CONSTRAINT [CK_NormativeDocument_DOCNAME] CHECK  ((len([DOCNAME])>=(1)))
GO
ALTER TABLE [dbo].[NormativeDocument] CHECK CONSTRAINT [CK_NormativeDocument_DOCNAME]
GO
ALTER TABLE [dbo].[NormativeDocument]  WITH NOCHECK ADD  CONSTRAINT [CK_NormativeDocument_DOCNUM] CHECK  ((len([DOCNUM])>=(1)))
GO
ALTER TABLE [dbo].[NormativeDocument] CHECK CONSTRAINT [CK_NormativeDocument_DOCNUM]
GO
ALTER TABLE [dbo].[Object]  WITH NOCHECK ADD  CONSTRAINT [CK_Object_CODE] CHECK  ((len([CODE])>=(0)))
GO
ALTER TABLE [dbo].[Object] CHECK CONSTRAINT [CK_Object_CODE]
GO
ALTER TABLE [dbo].[Object]  WITH NOCHECK ADD  CONSTRAINT [CK_Object_FORMALNAME] CHECK  ((len([FORMALNAME])>=(1)))
GO
ALTER TABLE [dbo].[Object] CHECK CONSTRAINT [CK_Object_FORMALNAME]
GO
ALTER TABLE [dbo].[Object]  WITH NOCHECK ADD  CONSTRAINT [CK_Object_LIVESTATUS] CHECK  (([LIVESTATUS]=(1) OR [LIVESTATUS]=(0)))
GO
ALTER TABLE [dbo].[Object] CHECK CONSTRAINT [CK_Object_LIVESTATUS]
GO
ALTER TABLE [dbo].[Object]  WITH NOCHECK ADD  CONSTRAINT [CK_Object_OFFNAME] CHECK  ((len([OFFNAME])>=(1)))
GO
ALTER TABLE [dbo].[Object] CHECK CONSTRAINT [CK_Object_OFFNAME]
GO
ALTER TABLE [dbo].[Object]  WITH NOCHECK ADD  CONSTRAINT [CK_Object_OKTMO] CHECK  ((len([OKTMO])>=(8)))
GO
ALTER TABLE [dbo].[Object] CHECK CONSTRAINT [CK_Object_OKTMO]
GO
ALTER TABLE [dbo].[Object]  WITH NOCHECK ADD  CONSTRAINT [CK_Object_PLAINCODE] CHECK  ((len([PLAINCODE])>=(0)))
GO
ALTER TABLE [dbo].[Object] CHECK CONSTRAINT [CK_Object_PLAINCODE]
GO
ALTER TABLE [dbo].[Object]  WITH NOCHECK ADD  CONSTRAINT [CK_Object_SHORTNAME] CHECK  ((len([SHORTNAME])>=(1)))
GO
ALTER TABLE [dbo].[Object] CHECK CONSTRAINT [CK_Object_SHORTNAME]
GO